### ISSUE TITLE
Explain more terminology

### ISSUE THREAD

**Issue by cabo** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#28]
Suffix: the whole thing we add to the IDTF to get an IXDTF
Suffix tag: Combination of suffix key and suffix value
Suffix key: ...
Suffix value: ...
Timezone suffix: The thing that we add before the suffix tags to get the timezone part of the suffix.  **Not a suffix tag**

* It would be nice to have a collective term for all suffix tags and the timezone suffix.  (We can talk about the information in there as "suffix information".)
* The unqualified "suffix" is a bit icky as we also have other suffixes (English sense) such as `Z`.

**Comment by ryzokuken** [comment]
@cabo how is Z a suffix? Isn't that part of the timestamp representing the offset?

**Comment by cabo** [comment]
Well, Z is a possible tail end ("suffix") of RFC 3339 dates, and that's what the definition in 1.2 tries to say.
Text in 1.2 copied from [RFC 3339, section 2](https://www.rfc-editor.org/rfc/rfc3339.html#section-2).

We of course can change that text to avoid the ickiness becoming apparent, but given that the two documents are meant to work together, I'd rather have a more specific term for the IXDTF suffix, so the word "suffix" stays available in its English sense.

**Comment by justingrant** [comment]
In Temporal we've called them "annotations" and "extensions". Not sure if either are better. 

I do agree with @ryzokuken that `Z` probably won't be confused for the extensions we're adding because an IDTF without `Z` will not be a valid IDTF string; it's no more or less a "suffix" than an offset like `+01:00`, and neither of them are suffixes _to_ IDTF strings but rather are a required part of those IDTF strings.

**Comment by brong** [comment]
@cabo will review and decide if we should close this

**Comment by cabo** [comment]
Note that this issue requires a more general editorial review, which also might include some more cherry-picking from #35.

**Comment by cabo** [comment]
Closing as overtaken by events.
