### ISSUE TITLE
Optimized for users or for programs?

### ISSUE THREAD

**Issue by cabo** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#5]
Did we ever say whether this is for human end-users or just an internal programming thing?  

In the latter case, we possibly can limit this to ASCII.  
In the former case, we are opening the big box of Pandora of UTF-8.

**Comment by justingrant** [comment]
In Temporal, we've assumed that these strings are primarily for consumption by software, not for display to end users. The fact that they're human-readable is important for easier debugging/logging purposes for developers or other technical readers, but we have no expectation that these strings should be meaningful for non-technical end users.  Furthermore, when there's a tradeoff between human readability and machine readability, the latter should almost always win.

A good example of this prioritization is timestamps with a calendar annotation. A more human-readable solution might show the day, month, and year in the context of the calendar. But a more machine-readable solution just shows the ISO 8601 date in the string, in order to maximize RFC 3339 compatibility and to enable programs to sort dates from multiple calendars on the same timeline.  In this case, the machine benefits of sorting and compatibility win out over the human benefit of being able to interpret the string within the context of a non-ISO calendar.
